# Generated by Django 5.0.6 on 2024-06-10 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название сферы вопросов')),
            ],
            options={
                'verbose_name': 'Сфера вопросов',
                'verbose_name_plural': 'Cферы вопросов',
                'ordering': ('name',),
                'default_related_name': 'scope',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=5000, verbose_name='Текст запроса')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Время и дата получения запроса')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор запроса')),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.scope', verbose_name='Сфера вопроса')),
            ],
            options={
                'verbose_name': 'Запрос',
                'verbose_name_plural': 'Запросы',
                'ordering': ('created',),
                'default_related_name': 'requests',
            },
        ),
        migrations.CreateModel(
            name='DocAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=5000, verbose_name='Типовой вопрос')),
                ('answer', models.CharField(max_length=5000, verbose_name='Ответ')),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.scope', verbose_name='Сфера вопроса')),
            ],
            options={
                'verbose_name': 'Типовой вопрос с примером',
                'verbose_name_plural': 'Типовые вопросы с примерами',
                'ordering': ('answer',),
                'default_related_name': 'docAnswers',
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=200, verbose_name='Слово')),
                ('requests', models.ManyToManyField(to='api.request', verbose_name='Запросы')),
            ],
            options={
                'verbose_name': 'Слово',
                'verbose_name_plural': 'Слова',
                'ordering': ('word',),
                'default_related_name': 'words',
            },
        ),
    ]
