# Generated by Django 5.0.6 on 2024-06-15 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=10000, verbose_name='Содержание ответа')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
            },
        ),
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Имя файла')),
                ('content', models.TextField(verbose_name='Содержание документа')),
            ],
            options={
                'verbose_name': 'Файл документации',
                'verbose_name_plural': 'Файлы документации',
            },
        ),
        migrations.CreateModel(
            name='Embedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('array_data', models.BinaryField(verbose_name='Бинарная информация')),
            ],
            options={
                'verbose_name': 'Embedding',
                'verbose_name_plural': 'Embedding',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=10000, verbose_name='Текст запроса')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Время и дата создания запроса')),
                ('answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.answer', verbose_name='Документация')),
            ],
            options={
                'verbose_name': 'Запрос',
                'verbose_name_plural': 'Запросы',
                'ordering': ('created',),
                'default_related_name': 'requests',
            },
        ),
    ]
