# Generated by Django 5.0.6 on 2024-06-10 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scope',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Название сферы вопросов'),
        ),
        migrations.AlterField(
            model_name='word',
            name='word',
            field=models.CharField(max_length=200, unique=True, verbose_name='Слово'),
        ),
        migrations.AddConstraint(
            model_name='docanswer',
            constraint=models.UniqueConstraint(fields=('question', 'answer'), name='unique_question_answer'),
        ),
        migrations.AddConstraint(
            model_name='docanswer',
            constraint=models.UniqueConstraint(fields=('question', 'answer', 'scope'), name='unique_question_answer_scope'),
        ),
    ]
