# Generated by Django 5.0.6 on 2024-06-12 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_request_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='requests',
        ),
        migrations.AddField(
            model_name='word',
            name='request',
            field=models.ForeignKey(default=100, on_delete=django.db.models.deletion.CASCADE, to='api.request', verbose_name='Запрос'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='word',
            name='word',
            field=models.CharField(max_length=200, verbose_name='Слово'),
        ),
    ]
